# Generated by Django 6.0.3 on 2026-03-21 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'cities',
                'db_table': 'cities_table',
            },
        ),
        migrations.CreateModel(
            name='CityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cities')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_image', to='city.city')),
            ],
            options={
                'db_table': 'cities_image_table',
            },
        ),
    ]
