# Generated by Django 6.0.3 on 2026-04-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_unique_lower_title'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='category',
            name='unique_lower_title',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
